spring:
  application:
    name: store
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 #5m
    refreshTokenExpiration: 604800 #7d
  profiles:
    active: prod
stripe:
  secret_key: ${STRIPE_SECRET_KEY}
  webhook_secret_key: ${STRIPE_WEBHOOK_SECRET_KEY}
google:
  redirect_url: ${REDIRECT_URL}
  auth:
    client_id: ${CLIENT_ID}
    client_secret: ${CLIENT_SECRET}
